
### 상담 등록
POST {{host}}/counsels
Content-Type: application/json

{
  "name": "이름",
  "cellPhone": "010*1111-2222",
  "email": "email@djdjdj.com",
  "memo": "메모 입력합니다!!!",
  "address": "서울 어딘구 어딘동",
  "addressDetail": "101동 101호",
  "zipCode": "12244"
}

### 상담 조회
GET {{host}}/counsels/1

### 상담 수정
PUT {{host}}/counsels/1
Content-Type: application/json

{
  "name": "이름2",
  "cellPhone": "010*1111-3333",
  "email": "email1@djdjdj.com",
  "memo": "메모 입력합니다!!!111",
  "address": "서울 어딘구 어딘동2",
  "addressDetail": "101동 101호2",
  "zipCode": "1224a"
}

### 상담 삭제
DELETE {{host}}/counsels/1